# Generated by Django 5.2.17 on 2026-09-29 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_missing_emails(apps, schema_editor):
    """Preenche e-mails vazios antes da constraint unique (dev/legado)."""
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(email=""):
        user.email = f"sem-email-{user.cpf}@placeholder.local"
        user.save(update_fields=["email"])
    for user in User.objects.filter(email__isnull=True):
        user.email = f"sem-email-{user.cpf}@placeholder.local"
        user.save(update_fields=["email"])


def unfill_missing_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(email__endswith="@placeholder.local").update(email="")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_default_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'professions',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(fill_missing_emails, unfill_missing_emails),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='E-mail do usuario (unico, usado para contato/recuperacao).', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoria do usuario (corresponde a profissao).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.category'),
        ),
        migrations.CreateModel(
            name='GranularPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'granular_permissions',
                'ordering': ['feature', 'action'],
                'constraints': [models.UniqueConstraint(fields=('feature', 'action'), name='uniq_permission_feature_action')],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='categories', to='accounts.granularpermission'),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('INACTIVATE', 'Inativação'), ('REACTIVATE', 'Reativação'), ('DELETE', 'Exclusão definitiva'), ('PROFESSION_CHANGE', 'Troca de profissão'), ('CATEGORY_CHANGE', 'Troca de categoria')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_subject_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
