# Generated by Django 5.2.17 on 2026-10-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_seed_care_plan_permissions"),
        ("care_plans", "0006_careplanhistory_actor_name_and_more"),
        ("care_scales", "0001_initial"),
        ("patients", "0006_healthcondition_name"),
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carescale",
            name="care_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_scales",
                to="care_plans.careplan",
            ),
        ),
        migrations.AddField(
            model_name="carescale",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_scales",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="ScaleNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scale_items",
                        to="care_plans.careplanneed",
                    ),
                ),
                (
                    "required_profession",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scale_requirements",
                        to="accounts.profession",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="care_scales.carescale",
                    ),
                ),
            ],
            options={
                "db_table": "care_scale_needs",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ScaleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scale_assignments",
                        to="professionals.professional",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="care_scales.scaleneed",
                    ),
                ),
            ],
            options={
                "db_table": "care_scale_assignments",
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="scaleneed",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("scale", "plan_need"),
                name="unique_current_scale_need",
            ),
        ),
        migrations.AddConstraint(
            model_name="scaleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("item", "professional"),
                name="unique_current_scale_professional",
            ),
        ),
    ]
