# Generated by Django 5.2.17 on 2026-10-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_seed_care_plan_permissions"),
        ("care_plans", "0006_careplanhistory_actor_name_and_more"),
        (
            "care_scales",
            "0002_carescale_care_plan_carescale_patient_scaleneed_and_more",
        ),
        ("patients", "0006_healthcondition_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="carescale",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carescale",
            name="observation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="carescale",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carescale",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Rascunho"),
                    ("ACTIVE", "Ativa"),
                    ("SUSPENDED", "Suspensa"),
                    ("CLOSED", "Encerrada"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="scaleneed",
            name="frequency_period",
            field=models.CharField(
                blank=True,
                choices=[("DAY", "Dia"), ("WEEK", "Semana"), ("MONTH", "Mês")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scaleneed",
            name="frequency_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scaleneed",
            name="frequency_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scaleneed",
            name="observation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scaleneed",
            name="planned_period",
            field=models.CharField(
                blank=True,
                choices=[("DAY", "Dia"), ("WEEK", "Semana"), ("MONTH", "Mês")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scaleneed",
            name="planned_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="carescale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "ACTIVE", "SUSPENDED", "CLOSED"])
                ),
                name="valid_care_scale_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="scaleneed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("frequency_quantity__isnull", True),
                    ("frequency_quantity__gt", 0),
                    _connector="OR",
                ),
                name="scale_need_positive_frequency",
            ),
        ),
        migrations.AddConstraint(
            model_name="scaleneed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("frequency_period__isnull", True),
                    ("frequency_period__in", ["DAY", "WEEK", "MONTH"]),
                    _connector="OR",
                ),
                name="scale_need_valid_period",
            ),
        ),
    ]
