# Generated by Django 5.2.17 on 2026-10-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care_scales", "0004_carescale_created_by_carescale_deleted_at_and_more"),
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalPlanningInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regions", models.JSONField(blank=True, default=list)),
                ("availability_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scale_planning",
                        to="professionals.professional",
                    ),
                ),
            ],
        ),
    ]
