# Generated by Django 5.2.17 on 2026-09-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='responsible_team',
            field=models.JSONField(blank=True, default=dict, help_text='Equipe responsavel (JSON provisorio ate TASK-CAD-PAC-005).', null=True),
        ),
    ]
