# Generated by Django 5.2.17 on 2026-09-28 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_responsible_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('INACTIVATE', 'Inativação'), ('REACTIVATE', 'Reativação'), ('DOCTOR_TEAM_CHANGE', 'Troca de médico/equipe')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
