# Generated by Django 5.2.17 on 2026-09-30 02:34
# Seed dos 8 tipos iniciais (RF-NEC-004) via RunPython idempotente.

from django.db import migrations, models


INITIAL_NEED_TYPES = [
    "Enfermagem",
    "Fisioterapia",
    "Médico",
    "Nutrição",
    "Terapia Ocupacional",
    "Fonoaudiologia",
    "Psicologia",
    "Outro",
]


def seed_need_types(apps, schema_editor):
    NeedType = apps.get_model("patients", "NeedType")
    for name in INITIAL_NEED_TYPES:
        NeedType.objects.get_or_create(
            name=name, defaults={"status": "ACTIVE"}
        )


def unseed_need_types(apps, schema_editor):
    NeedType = apps.get_model("patients", "NeedType")
    NeedType.objects.filter(name__in=INITIAL_NEED_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_needtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needtype',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], default='ACTIVE', max_length=10),
        ),
        migrations.RunPython(seed_need_types, unseed_need_types),
    ]
