# Generated by Django 5.2.17 on 2026-10-08 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_careneed_inactivated_at_careneed_is_active_and_more"),
        ("care_plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarePlanNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("removal_reason", models.TextField(blank=True)),
                (
                    "care_need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_plan_links",
                        to="assessments.careneed",
                    ),
                ),
                (
                    "care_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="need_links",
                        to="care_plans.careplan",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_care_plan_needs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "care_plan_needs",
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=("care_plan", "care_need"),
                        name="unique_current_plan_need",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("removal_reason", ""),
                                ("removed_at__isnull", True),
                                ("removed_by__isnull", True),
                            ),
                            models.Q(
                                ("removed_at__isnull", False),
                                models.Q(("removal_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="care_plan_need_removal_metadata",
                    ),
                ],
            },
        ),
    ]
