# Generated by Django 5.2.17 on 2026-10-08 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_careneed_inactivated_at_careneed_is_active_and_more"),
        ("care_plans", "0002_careplanneed"),
        ("professionals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="careplanneed",
            name="frequency_period",
            field=models.CharField(
                blank=True,
                choices=[("DAY", "Dia"), ("WEEK", "Semana"), ("MONTH", "Mês")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="careplanneed",
            name="frequency_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="careplanneed",
            name="required_professional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_plan_needs",
                to="professionals.professional",
            ),
        ),
        migrations.AddConstraint(
            model_name="careplanneed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("frequency_quantity__isnull", True),
                    ("frequency_quantity__gt", 0),
                    _connector="OR",
                ),
                name="care_plan_need_positive_frequency",
            ),
        ),
        migrations.AddConstraint(
            model_name="careplanneed",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("frequency_period__isnull", True),
                    ("frequency_period__in", ["DAY", "WEEK", "MONTH"]),
                    _connector="OR",
                ),
                name="care_plan_need_valid_frequency_period",
            ),
        ),
    ]
