# Generated by Django 5.2.17 on 2026-10-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_careneed_inactivated_at_careneed_is_active_and_more"),
        ("care_plans", "0003_careplanneed_frequency_period_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarePlanNeedResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("observation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="care_plans.careplanneed",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_plan_resources",
                        to="assessments.resource",
                    ),
                ),
            ],
            options={
                "db_table": "care_plan_need_resources",
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="care_plan_resource_positive_quantity",
                    )
                ],
            },
        ),
    ]
