# Generated by Django 5.2.17 on 2026-10-08 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care_plans", "0004_careplanneedresource"),
        ("patients", "0006_healthcondition_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="careplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("patient",),
                name="unique_active_plan_patient",
            ),
        ),
    ]
