# Generated by Django 5.2.17 on 2026-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care_plans", "0005_careplan_unique_active_plan_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="careplanhistory",
            name="actor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="careplanhistory",
            name="event_type",
            field=models.CharField(default="UPDATE", max_length=30),
        ),
    ]
