# Generated by Django 5.2.17 on 2026-09-30 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_alter_needtype_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('INITIAL', 'Avaliação inicial')], default='INITIAL', max_length=10)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('assessment_time', models.TimeField(blank=True, null=True)),
                ('request_origin', models.CharField(blank=True, max_length=50)),
                ('administrative_observations', models.TextField(blank=True)),
                ('request_reason', models.TextField(blank=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('initial_need_description', models.TextField(blank=True)),
                ('need_start_date', models.DateField(blank=True, null=True)),
                ('anamnesis', models.TextField(blank=True)),
                ('hda', models.TextField(blank=True)),
                ('current_condition', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('relevant_information', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='patients.patient')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_assessments',
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], max_length=10)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identificada')], default='IDENTIFIED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_needs', to='patients.needtype')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_needs', to='assessments.patientassessment')),
            ],
            options={
                'db_table': 'care_needs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_resources', to='assessments.patientassessment')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_resources', to='assessments.resource')),
            ],
            options={
                'db_table': 'assessment_resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
