# Generated by Django 5.2.17 on 2026-10-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassessment',
            name='request_origin',
            field=models.CharField(blank=True, choices=[('Família', 'Família'), ('Médico', 'Médico'), ('Hospital', 'Hospital'), ('Clínica', 'Clínica'), ('Outro', 'Outro')], max_length=50),
        ),
    ]
